const dummyServiceProviders = [
  // Indore (5 providers)
  {
    name: "Amit Sharma",
    email: "amit.sharma@gmail.com",
    password: "password123",
    phone: "9876543210",
    title: "Electrician",
    skills: ["Wiring", "Appliance Repair", "Circuit Installation"],
    location: {
      city: "Indore",
      pin: "452001",
      coordinates: [75.8577, 22.7196], // Approx Indore coordinates
    },
    availability: [
      { day: "Monday", timeSlots: ["9AM-12PM", "2PM-5PM"] },
      { day: "Wednesday", timeSlots: ["10AM-1PM"] },
    ],
    isAvailable: true,
    rating: 4.5,
    totalReviews: 20,
    createdAt: new Date("2025-01-15"),
  },
  {
    name: "Priya Patel",
    email: "priya.patel@gmail.com",
    password: "securepass456",
    phone: "9123456789",
    title: "Plumber",
    skills: ["Pipe Repair", "Leak Detection", "Water Heater Installation"],
    location: {
      city: "Indore",
      pin: "452007",
      coordinates: [75.8500, 22.7200],
    },
    availability: [
      { day: "Tuesday", timeSlots: ["8AM-11AM", "3PM-6PM"] },
      { day: "Friday", timeSlots: ["9AM-2PM"] },
    ],
    isAvailable: true,
    rating: 4.2,
    totalReviews: 15,
    createdAt: new Date("2025-02-01"),
  },
  {
    name: "Rahul Verma",
    email: "rahul.verma@gmail.com",
    password: "rahul7890",
    phone: "9988776655",
    title: "Carpenter",
    skills: ["Furniture Making", "Wood Polishing", "Cabinet Installation"],
    location: {
      city: "Indore",
      pin: "452003",
      coordinates: [75.8600, 22.7100],
    },
    availability: [
      { day: "Thursday", timeSlots: ["10AM-3PM"] },
      { day: "Saturday", timeSlots: ["9AM-1PM", "4PM-7PM"] },
    ],
    isAvailable: false,
    rating: 3.8,
    totalReviews: 10,
    createdAt: new Date("2025-03-10"),
  },
  {
    name: "Sneha Gupta",
    email: "sneha.gupta@gmail.com",
    password: "sneha2025",
    phone: "9871234567",
    title: "Painter",
    skills: ["Wall Painting", "Texture Painting", "Exterior Painting"],
    location: {
      city: "Indore",
      pin: "452009",
      coordinates: [75.8550, 22.7150],
    },
    availability: [
      { day: "Monday", timeSlots: ["8AM-12PM"] },
      { day: "Sunday", timeSlots: ["10AM-2PM"] },
    ],
    isAvailable: true,
    rating: 4.0,
    totalReviews: 8,
    createdAt: new Date("2025-04-05"),
  },
  {
    name: "Vikram Singh",
    email: "vikram.singh@gmail.com",
    password: "vikram123",
    phone: "9765432109",
    title: "Gardener",
    skills: ["Landscaping", "Plant Care", "Lawn Maintenance"],
    location: {
      city: "Indore",
      pin: "452011",
      coordinates: [75.8620, 22.7250],
    },
    availability: [
      { day: "Wednesday", timeSlots: ["7AM-10AM"] },
      { day: "Saturday", timeSlots: ["8AM-11AM"] },
    ],
    isAvailable: true,
    rating: 4.7,
    totalReviews: 25,
    createdAt: new Date("2025-02-20"),
  },

  // Bhopal (5 providers)
  {
    name: "Anjali Jain",
    email: "anjali.jain@gmail.com",
    password: "anjali456",
    phone: "9876541234",
    title: "AC Technician",
    skills: ["AC Repair", "Cooling System Installation", "Maintenance"],
    location: {
      city: "Bhopal",
      pin: "462001",
      coordinates: [77.4126, 23.2599], // Approx Bhopal coordinates
    },
    availability: [
      { day: "Tuesday", timeSlots: ["9AM-1PM", "2PM-5PM"] },
      { day: "Thursday", timeSlots: ["10AM-3PM"] },
    ],
    isAvailable: true,
    rating: 4.3,
    totalReviews: 12,
    createdAt: new Date("2025-01-20"),
  },
  {
    name: "Rohit Malhotra",
    email: "rohit.malhotra@gmail.com",
    password: "rohit789",
    phone: "9123459876",
    title: "Mason",
    skills: ["Bricklaying", "Concrete Work", "Tile Installation"],
    location: {
      city: "Bhopal",
      pin: "462003",
      coordinates: [77.4100, 23.2600],
    },
    availability: [
      { day: "Friday", timeSlots: ["8AM-12PM"] },
      { day: "Sunday", timeSlots: ["9AM-2PM"] },
    ],
    isAvailable: true,
    rating: 4.1,
    totalReviews: 18,
    createdAt: new Date("2025-03-15"),
  },
  {
    name: "Kavita Reddy",
    email: "kavita.reddy@gmail.com",
    password: "kavita2025",
    phone: "9988665544",
    title: "Cleaner",
    skills: ["House Cleaning", "Office Cleaning", "Deep Cleaning"],
    location: {
      city: "Bhopal",
      pin: "462026",
      coordinates: [77.4150, 23.2550],
    },
    availability: [
      { day: "Monday", timeSlots: ["7AM-11AM"] },
      { day: "Saturday", timeSlots: ["8AM-12PM"] },
    ],
    isAvailable: false,
    rating: 3.9,
    totalReviews: 9,
    createdAt: new Date("2025-04-10"),
  },
  {
    name: "Suresh Yadav",
    email: "suresh.yadav@gmail.com",
    password: "suresh123",
    phone: "9876540987",
    title: "Electrician",
    skills: ["Wiring", "Lighting Installation", "Panel Repair"],
    location: {
      city: "Bhopal",
      pin: "462030",
      coordinates: [77.4200, 23.2650],
    },
    availability: [
      { day: "Wednesday", timeSlots: ["9AM-1PM", "3PM-6PM"] },
      { day: "Friday", timeSlots: ["10AM-2PM"] },
    ],
    isAvailable: true,
    rating: 4.6,
    totalReviews: 22,
    createdAt: new Date("2025-02-25"),
  },
  {
    name: "Meena Thakur",
    email: "meena.thakur@gmail.com",
    password: "meena456",
    phone: "9765431234",
    title: "Interior Designer",
    skills: ["Space Planning", "Color Consultation", "Furniture Design"],
    location: {
      city: "Bhopal",
      pin: "462042",
      coordinates: [77.4000, 23.2700],
    },
    availability: [
      { day: "Thursday", timeSlots: ["10AM-1PM"] },
      { day: "Sunday", timeSlots: ["11AM-3PM"] },
    ],
    isAvailable: true,
    rating: 4.8,
    totalReviews: 30,
    createdAt: new Date("2025-01-30"),
  },

  // Ujjain (5 providers)
  {
    name: "Vivek Joshi",
    email: "vivek.joshi@gmail.com",
    password: "vivek789",
    phone: "9876545678",
    title: "Plumber",
    skills: ["Pipe Installation", "Drain Cleaning", "Bathroom Fixtures"],
    location: {
      city: "Ujjain",
      pin: "456001",
      coordinates: [75.7764, 23.1793], // Approx Ujjain coordinates
    },
    availability: [
      { day: "Monday", timeSlots: ["8AM-11AM", "2PM-5PM"] },
      { day: "Thursday", timeSlots: ["9AM-12PM"] },
    ],
    isAvailable: true,
    rating: 4.4,
    totalReviews: 14,
    createdAt: new Date("2025-02-05"),
  },
  {
    name: "Pooja Dubey",
    email: "pooja.dubey@gmail.com",
    password: "pooja2025",
    phone: "9123454321",
    title: "Electrician",
    skills: ["Home Wiring", "Inverter Installation", "Appliance Repair"],
    location: {
      city: "Ujjain",
      pin: "456006",
      coordinates: [75.7800, 23.1800],
    },
    availability: [
      { day: "Tuesday", timeSlots: ["10AM-2PM"] },
      { day: "Saturday", timeSlots: ["8AM-12PM"] },
    ],
    isAvailable: true,
    rating: 4.0,
    totalReviews: 11,
    createdAt: new Date("2025-03-20"),
  },
  {
    name: "Arjun Rathore",
    email: "arjun.rathore@gmail.com",
    password: "arjun123",
    phone: "9988771234",
    title: "Carpenter",
    skills: ["Furniture Repair", "Wood Carving", "Door Installation"],
    location: {
      city: "Ujjain",
      pin: "456010",
      coordinates: [75.7700, 23.1750],
    },
    availability: [
      { day: "Wednesday", timeSlots: ["9AM-1PM"] },
      { day: "Friday", timeSlots: ["10AM-3PM"] },
    ],
    isAvailable: false,
    rating: 3.7,
    totalReviews: 7,
    createdAt: new Date("2025-04-15"),
  },
  {
    name: "Neha Agrawal",
    email: "neha.agrawal@gmail.com",
    password: "neha456",
    phone: "9876543211",
    title: "Painter",
    skills: ["Interior Painting", "Wall Art", "Waterproofing"],
    location: {
      city: "Ujjain",
      pin: "456440",
      coordinates: [75.7850, 23.1850],
    },
    availability: [
      { day: "Monday", timeSlots: ["8AM-12PM"] },
      { day: "Sunday", timeSlots: ["9AM-1PM"] },
    ],
    isAvailable: true,
    rating: 4.2,
    totalReviews: 16,
    createdAt: new Date("2025-02-10"),
  },
  {
    name: "Mohan Lal",
    email: "mohan.lal@gmail.com",
    password: "mohan789",
    phone: "9765439876",
    title: "Gardener",
    skills: ["Tree Trimming", "Garden Design", "Plant Maintenance"],
    location: {
      city: "Ujjain",
      pin: "456664",
      coordinates: [75.7900, 23.1900],
    },
    availability: [
      { day: "Tuesday", timeSlots: ["7AM-10AM"] },
      { day: "Saturday", timeSlots: ["8AM-11AM"] },
    ],
    isAvailable: true,
    rating: 4.5,
    totalReviews: 20,
    createdAt: new Date("2025-01-25"),
  },
];

module.exports = dummyServiceProviders;